title: Cookbook
email: johnensley17@gmail.com
description: >-
  This is a collection of recipes we like to make.
baseurl: ""
url: "https://cookbook.john-ensley.com"
twitter_username: john__ensley
github_username:  ensley

theme: minima
plugins:
  - jekyll-feed

collections:
  recipes:
    output: true
    permalink: /:name:output_ext
