version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install jekyll bundler
  build:
    commands:
      - echo "********* Building Jekyll Site *********"
      - bundle install
      - bundle exec jekyll build
      - echo "*********   Uploading to S3    *********"
      - aws s3 sync _site/ s3://john-ensley.com